// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDniTKZEOGYOe0TV1mBDmmxUQO3wy1NjUA',
    appId: '1:338717647096:web:50beac3211e71a862f9b0d',
    messagingSenderId: '338717647096',
    projectId: 'kegiatanone-praktikum',
    authDomain: 'kegiatanone-praktikum.firebaseapp.com',
    storageBucket: 'kegiatanone-praktikum.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL-LL-QI7FhafLd_toQ7Cz8QlRe-wLqLM',
    appId: '1:338717647096:android:fb182d3be41a24782f9b0d',
    messagingSenderId: '338717647096',
    projectId: 'kegiatanone-praktikum',
    storageBucket: 'kegiatanone-praktikum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdbu5OaXmbfAQLr108gycDH4yieTuI4Q0',
    appId: '1:338717647096:ios:131cab9894e3782b2f9b0d',
    messagingSenderId: '338717647096',
    projectId: 'kegiatanone-praktikum',
    storageBucket: 'kegiatanone-praktikum.appspot.com',
    iosClientId: '338717647096-hv7c81b96frf4s6l7jl8ssi8922vn77a.apps.googleusercontent.com',
    iosBundleId: 'com.example.kegiatantwo',
  );
}
